using AutoMapper;
using SalesforceAPI.Dtos;
using SalesforceAPI.Models;
namespace SalesforceAPI.Profiles
{
    public class DtoProfile: Profile
    {
        public DtoProfile()
        {
            CreateMap<PractitionerFull, PractitionerFullDto>();
            CreateMap<PractitionerFullDto, PractitionerFull>();

            CreateMap<OrganizationFull, OrganizationFullDto>();
            CreateMap<OrganizationFullDto, OrganizationFull>();

            CreateMap<ApplicationUser, UserDto>().ReverseMap();


            CreateMap<CredentialingContact, CredentialingContactDto>()
                .ForMember(dest => dest.Contact_First_Name__c, opt => opt.MapFrom(src => src.ContactFirstName))
                .ForMember(dest => dest.Contact_Last_Name__c, opt => opt.MapFrom(src => src.ContactLastName))
                .ForMember(dest => dest.Contact_Email__c, opt => opt.MapFrom(src => src.ContactEmail))
                .ForMember(dest => dest.Contact_Person_Role__c, opt => opt.MapFrom(src => src.ContactPersonRole))
                .ForMember(dest => dest.Contact_Phone__c, opt => opt.MapFrom(src => src.ContactPhone))
                .ForMember(dest => dest.Primary_Contact__c, opt => opt.MapFrom(src => src.PrimaryContact))
                .ForMember(dest => dest.Credentialing_Profile_Id__c, opt => opt.MapFrom(src => src.CredentialingProfileId));

            CreateMap<ServiceLocation, ServiceLocationDto>()
                .ForMember(dest => dest.Credentialing_Profile__c, opt => opt.MapFrom(src => src.CredentialingProfileId))
                .ForMember(dest => dest.Account_Site__c, opt => opt.MapFrom(src => src.AccountSite))
                .ForMember(dest => dest.Account__c, opt => opt.MapFrom(src => src.Account))
                .ForMember(dest => dest.Facility_License_if_applicable__c, opt => opt.MapFrom(src => src.FacilityLicenseifapplicable))
                .ForMember(dest => dest.Facility_License_Expiration_if_applicab__c, opt => opt.MapFrom(src => src.FacilityLicenseExpirationifapplicab))
                .ForMember(dest => dest.Facility_License_Number_if_applicable__c, opt => opt.MapFrom(src => src.FacilityLicenseNumberifapplicable))
                .ForMember(dest => dest.Facility_License_Status_if_applicable__c, opt => opt.MapFrom(src => src.FacilityLicenseStatusifapplicable))
                .ForMember(dest => dest.Hours_of_Operation__c, opt => opt.MapFrom(src => src.HoursofOperation))
                .ForMember(dest => dest.Accomodations_Accessibility__c, opt => opt.MapFrom(src => src.AccomodationsAccessibility))
                .ForMember(dest => dest.Accomodations_Accessibility_Other__c, opt => opt.MapFrom(src => src.AccomodationsAccessibilityOther))
                .ForMember(dest => dest.Licensed_Facility__c, opt => opt.MapFrom(src => src.LicensedFacility));

            CreateMap<ServiceLocationLicense, ServiceLocationLicenseDto>()
            .ForMember(dest => dest.Credentialing_Profile__c, opt => opt.MapFrom(src => src.CredentialingProfileId))
            .ForMember(dest => dest.Service_Locations__c, opt => opt.MapFrom(src => src.ServiceLocations))
            .ForMember(dest => dest.Service_Name__c, opt => opt.MapFrom(src => src.ServiceName))
            .ForMember(dest => dest.Service_License_Expiration_if_applicabl__c, opt => opt.MapFrom(src => src.ServiceLicenseExpirationifapplicabl))
            .ForMember(dest => dest.Service_License_Number_if_applicable__c, opt => opt.MapFrom(src => src.ServiceLicenseNumberifapplicable))
            .ForMember(dest => dest.Service_License_Status_if_applicable__c, opt => opt.MapFrom(src => src.ServiceLicenseStatusifapplicable));

            CreateMap<DirectService, DirectServiceDto>()
                .ForMember(dest => dest.Operator__c, opt => opt.MapFrom(src => src.Operator))
                .ForMember(dest => dest.Service__c, opt => opt.MapFrom(src => src.Service))
                .ForMember(dest => dest.is_Certification__c, opt => opt.MapFrom(src => src.IsCertification));        

            CreateMap<OrganizationalPSV, OrganizationalPSVDto>()
                .ForMember(dest => dest.Credentialing_Profile__c, opt => opt.MapFrom(src => src.CredentialingProfile))
                .ForMember(dest => dest.Primary_Source_Verifier__c, opt => opt.MapFrom(src => src.PrimarySourceVerifier))
                .ForMember(dest => dest.CVO__c, opt => opt.MapFrom(src => src.CVO))
                .ForMember(dest => dest.Other_Accred__c, opt => opt.MapFrom(src => src.OtherAccred))
                .ForMember(dest => dest.Verifier_s_Credentialing_Organization__c, opt => opt.MapFrom(src => src.VerifiersCredentialingOrganization))
                .ForMember(dest => dest.LARA_License__c, opt => opt.MapFrom(src => src.LARALicense))
                .ForMember(dest => dest.LARA_Uploaded__c, opt => opt.MapFrom(src => src.LARAUploaded))
                .ForMember(dest => dest.Proof_of_Accreditation__c, opt => opt.MapFrom(src => src.ProofofAccreditation))
                .ForMember(dest => dest.Disciplinary_status_with_regulatory_boar__c, opt => opt.MapFrom(src => src.Disciplinarystatuswithregulatoryboar))
                .ForMember(dest => dest.MDHHS_Sanctioned_Provider_Check__c, opt => opt.MapFrom(src => src.MDHHSSanctionedProviderCheck))
                .ForMember(dest => dest.At_least_five_year_history_of_organizati__c, opt => opt.MapFrom(src => src.Atleastfiveyearhistoryoforganizati))
                .ForMember(dest => dest.On_Site_Quality_Assessment_Recredential__c, opt => opt.MapFrom(src => src.OnSiteQualityAssessmentRecredential))
                .ForMember(dest => dest.Office_of_Inspector_General_Check__c, opt => opt.MapFrom(src => src.OfficeofInspectorGeneralCheck))
                .ForMember(dest => dest.SAM_gov_Check__c, opt => opt.MapFrom(src => src.SAMgovCheck));

            CreateMap<OrganizationalCP, OrganizationalCPDto>()
                .ForMember(dest => dest.Accreditation_End__c, opt => opt.MapFrom(src => src.AccreditationEnd))
                .ForMember(dest => dest.Accreditation_Start__c, opt => opt.MapFrom(src => src.AccreditationStart))
                .ForMember(dest => dest.Accrediting_Body__c, opt => opt.MapFrom(src => src.AccreditingBody))
                .ForMember(dest => dest.Proof_of_Accreditation_Status__c, opt => opt.MapFrom(src => src.ProofofAccreditationStatus))
                .ForMember(dest => dest.When_was_the_last_accreditation_survey__c, opt => opt.MapFrom(src => src.Whenwasthelastaccreditationsurvey))
                .ForMember(dest => dest.Date_of_Birth__c, opt => opt.MapFrom(src => src.DateofBirth))
                .ForMember(dest => dest.Tax_ID__c, opt => opt.MapFrom(src => src.TaxID))
                .ForMember(dest => dest.Medicare_Provider__c, opt => opt.MapFrom(src => src.MedicareProvider))
                .ForMember(dest => dest.Medicare_Number__c, opt => opt.MapFrom(src => src.MedicareNumber))
                .ForMember(dest => dest.Practitioner_NPI__c, opt => opt.MapFrom(src => src.NPI))
                .ForMember(dest => dest.Office_Address_Street_1__c, opt => opt.MapFrom(src => src.OfficeAddressStreet1))
                .ForMember(dest => dest.Office_Address_City__c, opt => opt.MapFrom(src => src.OfficeAddressCity))
                .ForMember(dest => dest.Office_Address_Zipcode__c, opt => opt.MapFrom(src => src.OfficeAddressZipcode))
                .ForMember(dest => dest.Office_Address_State__c, opt => opt.MapFrom(src => src.OfficeAddressState))
                .ForMember(dest => dest.Office_Address_County__c, opt => opt.MapFrom(src => src.OfficeAddressCounty))
                .ForMember(dest => dest.Home_Address_Street_1__c, opt => opt.MapFrom(src => src.HomeAddressStreet1))
                .ForMember(dest => dest.Home_Address_City__c, opt => opt.MapFrom(src => src.HomeAddressCity))
                .ForMember(dest => dest.Home_Address_Zipcode__c, opt => opt.MapFrom(src => src.HomeAddressZipcode))
                .ForMember(dest => dest.Home_Address_State__c, opt => opt.MapFrom(src => src.HomeAddressState))
                .ForMember(dest => dest.Home_Address_County__c, opt => opt.MapFrom(src => src.HomeAddressCounty))
                .ForMember(dest => dest.Specialties__c, opt => opt.MapFrom(src => src.Specialties))
                .ForMember(dest => dest.Specialty_Other__c, opt => opt.MapFrom(src => src.OtherSpecialty))
                .ForMember(dest => dest.Certificate_of_Liability__c, opt => opt.MapFrom(src => src.CertificateofLiability))
                .ForMember(dest => dest.Certificate_of_Liability_Expiration_Date__c, opt => opt.MapFrom(src => src.CertificateofLiabilityExpirationDate))
                .ForMember(dest => dest.Languages_Spoken__c, opt => opt.MapFrom(src => src.LanguagesSpoken))
                .ForMember(dest => dest.Cultural_Competences__c, opt => opt.MapFrom(src => src.CulturalCompetences))
                .ForMember(dest => dest.X6_month_gap_in_employment_since_profess__c, opt => opt.MapFrom(src => src.X6monthgapinemploymentsinceprofess))
                .ForMember(dest => dest.X6_Month_Gap_Start_Date__c, opt => opt.MapFrom(src => src.X6MonthGapStartDate))
                .ForMember(dest => dest.X6_Month_Gap_End_Date__c, opt => opt.MapFrom(src => src.X6MonthGapEndDate))
                .ForMember(dest => dest.X6_Month_Gap_Activity__c, opt => opt.MapFrom(src => src.X6MonthGapActivity))
                .ForMember(dest => dest.X6_Month_Gap_Reason__c, opt => opt.MapFrom(src => src.X6MonthGapReason))
                .ForMember(dest => dest.Please_acknowledge_If_denied_credential__c, opt => opt.MapFrom(src => src.PleaseacknowledgeIfdeniedcredential))
                .ForMember(dest => dest.Can_you_perform_the_essential_duties_of__c, opt => opt.MapFrom(src => src.Canyouperformtheessentialdutiesof))
                .ForMember(dest => dest.Lack_of_present_illegal_drug_use__c, opt => opt.MapFrom(src => src.Lackofpresentillegaldruguse))
                .ForMember(dest => dest.History_of_loss_of_license__c, opt => opt.MapFrom(src => src.Historyoflossoflicense))
                .ForMember(dest => dest.History_of_felony_convictions__c, opt => opt.MapFrom(src => src.Historyoffelonyconvictions))
                .ForMember(dest => dest.History_of_loss_or_limitations_of_privil__c, opt => opt.MapFrom(src => src.Historyoflossorlimitationsofprivil))
                .ForMember(dest => dest.ExplanationHistory_of_felony_convictions__c, opt => opt.MapFrom(src => src.ExplanationHistoryoffelonyconvictions))
                .ForMember(dest => dest.Current_Malpractice_Insurance_Coverage__c, opt => opt.MapFrom(src => src.CurrentMalpracticeInsuranceCoverage))
                .ForMember(dest => dest.Attestation_by_the_applicant_of_the_corr__c, opt => opt.MapFrom(src => src.Attestationbytheapplicantofthecorr))
                .ForMember(dest => dest.Office_Phone_Number__c, opt => opt.MapFrom(src => src.OfficePhoneNumber))
                .ForMember(dest => dest.Email__c, opt => opt.MapFrom(src => src.Email))
                .ForMember(dest => dest.Cultural_Competencies_Picklist__c, opt => opt.MapFrom(src => src.CulturalCompetenciesPicklist))
                .ForMember(dest => dest.W9_Expiration__c, opt => opt.MapFrom(src => src.W9Expiration))
                .ForMember(dest => dest.W9_Status__c, opt => opt.MapFrom(src => src.W9Status))
                .ForMember(dest => dest.Disclosure_Form_Expiration__c, opt => opt.MapFrom(src => src.DisclosureFormExpiration))
                .ForMember(dest => dest.Professional_Liability_Expiration__c, opt => opt.MapFrom(src => src.ProfessionalLiabilityExpiration))
                .ForMember(dest => dest.Commercial_Liability_Expiration__c, opt => opt.MapFrom(src => src.CommercialLiabilityExpiration))
                .ForMember(dest => dest.Workers_Compensation_Expiration__c, opt => opt.MapFrom(src => src.WorkersCompensationExpiration))
                .ForMember(dest => dest.Five_year_history_org_liability__c, opt => opt.MapFrom(src => src.Fiveyearhistoryorgliability))
                .ForMember(dest => dest.Explanation_five_year_history__c, opt => opt.MapFrom(src => src.Explanationfiveyearhistory))
                .ForMember(dest => dest.Action_pending_org_license__c, opt => opt.MapFrom(src => src.Actionpendingorglicense))
                .ForMember(dest => dest.Explanation_org_license__c, opt => opt.MapFrom(src => src.Explanationorglicense))
                .ForMember(dest => dest.Org_accreditation_limited__c, opt => opt.MapFrom(src => src.Orgaccreditationlimited))
                .ForMember(dest => dest.Explanation_org_accreditation_limited__c, opt => opt.MapFrom(src => src.Explanationorgaccreditationlimited))
                .ForMember(dest => dest.Action_pending_current_accreditation__c, opt => opt.MapFrom(src => src.Actionpendingcurrentaccreditation))
                .ForMember(dest => dest.Explanation_current_accreditation__c, opt => opt.MapFrom(src => src.Explanationcurrentaccreditation))
                .ForMember(dest => dest.Org_medicaid_sanctions__c, opt => opt.MapFrom(src => src.Orgmedicaidsanctions))
                .ForMember(dest => dest.Org_medicare_sanctions__c, opt => opt.MapFrom(src => src.Orgmedicaresanctions))
                .ForMember(dest => dest.Explanation_org_medicaid_sanctions__c, opt => opt.MapFrom(src => src.Explanationorgmedicaidsanctions))
                .ForMember(dest => dest.Explanation_org_medicare_sanctions__c, opt => opt.MapFrom(src => src.Explanationorgmedicaresanctions))
                .ForMember(dest => dest.Org_insurance_initially_refused__c, opt => opt.MapFrom(src => src.Orginsuranceinitiallyrefused))
                .ForMember(dest => dest.Explanation_org_insurance_initially_refu__c, opt => opt.MapFrom(src => src.Explanationorginsuranceinitiallyrefused))
                .ForMember(dest => dest.Org_defendant_SUD_payment__c, opt => opt.MapFrom(src => src.OrgdefendantSUDpayment))
                .ForMember(dest => dest.Explanation_org_defendant_SUD_payment__c, opt => opt.MapFrom(src => src.ExplanationorgdefendantSUDpayment))
                .ForMember(dest => dest.Org_malpractice_claims_SUD__c, opt => opt.MapFrom(src => src.OrgmalpracticeclaimsSUD))
                .ForMember(dest => dest.Explanation_org_malpractice_claims_SUD__c, opt => opt.MapFrom(src => src.ExplanationorgmalpracticeclaimsSUD))
                .ForMember(dest => dest.Please_indicate_if_you_have_a_speciality__c, opt => opt.MapFrom(src => src.Pleaseindicateifyouhaveaspeciality))
                .ForMember(dest => dest.Proof_of_Accreditation__c, opt => opt.MapFrom(src => src.ProofofAccreditation))
                .ForMember(dest => dest.Cyber_Liability_if_applicable__c, opt => opt.MapFrom(src => src.CyberLiabilityifapplicable))
                .ForMember(dest => dest.Commercial_Liability__c, opt => opt.MapFrom(src => src.CommercialLiability))
                .ForMember(dest => dest.Proof_of_Accreditation_Expiration__c, opt => opt.MapFrom(src => src.ProofofAccreditationExpiration))
                .ForMember(dest => dest.Cyber_Liability_Expiration_if_applicabl__c, opt => opt.MapFrom(src => src.CyberLiabilityExpirationifapplicable))
                .ForMember(dest => dest.Cyber_Liability_Status_if_applicable__c, opt => opt.MapFrom(src => src.CyberLiabilityStatusifapplicable))
                .ForMember(dest => dest.Disclosure_Form_Status__c, opt => opt.MapFrom(src => src.DisclosureFormStatus)).ReverseMap();

            CreateMap<Education, EducationDto>()
                .ForMember(dest => dest.College_University_Program_Address__c, opt => opt.MapFrom(src => src.CollegeUniversityProgramAddress))
                .ForMember(dest => dest.College_University_Program_Name__c, opt => opt.MapFrom(src => src.CollegeUniversityProgramName))
                .ForMember(dest => dest.Credentialing_Profile_ID__c, opt => opt.MapFrom(src => src.CredentialingProfileID))
                .ForMember(dest => dest.Degree__c, opt => opt.MapFrom(src => src.Degree))
                .ForMember(dest => dest.Graduation_Date__c, opt => opt.MapFrom(src => src.GraduationDate)).ReverseMap();

            CreateMap<HospitalAffiliation, HospitalAffiliationDto>()
                .ForMember(dest => dest.Hospital_Affiliation_Address__c, opt => opt.MapFrom(src => src.HospitalAffiliationAddress))
                .ForMember(dest => dest.Hospital_Affiliation_Name__c, opt => opt.MapFrom(src => src.HospitalAffiliationName))
                .ForMember(dest => dest.Category_of_Membership__c, opt => opt.MapFrom(src => src.CategoryofMembership))
                .ForMember(dest => dest.Start_Date_of_Affiliation__c, opt => opt.MapFrom(src => src.StartDateofAffiliation))
                .ForMember(dest => dest.End_Date_of_Affiliation__c, opt => opt.MapFrom(src => src.EndDateofAffiliation)).ReverseMap();

            CreateMap<PGMedicalTraining, PGMedicalTrainingDto>()
                .ForMember(dest => dest.Credentialing_Profile_Id__c, opt => opt.MapFrom(src => src.CredentialingProfileId))
                .ForMember(dest => dest.Medical_Training_Hospital_Address__c, opt => opt.MapFrom(src => src.MedicalTrainingHospitalAddress))
                .ForMember(dest => dest.Medical_Training_Hospital_Name__c, opt => opt.MapFrom(src => src.MedicalTrainingHospitalName))
                .ForMember(dest => dest.Medical_Training_Type__c, opt => opt.MapFrom(src => src.MedicalTrainingType))
                .ForMember(dest => dest.Specialty__c, opt => opt.MapFrom(src => src.Specialty))
                .ForMember(dest => dest.Training_End_Date__c, opt => opt.MapFrom(src => src.TrainingEndDate))
                .ForMember(dest => dest.Training_Start_Date__c, opt => opt.MapFrom(src => src.TrainingStartDate)).ReverseMap();

            CreateMap<PractitionerLC, PractitionerLCDto>()
                .ForMember(dest => dest.RecordTypeId, opt => opt.MapFrom(src => src.RecordTypeId))
                .ForMember(dest => dest.Credentialing_Profile_Id__c, opt => opt.MapFrom(src => src.CredentialingProfileId))
                .ForMember(dest => dest.Expiration_Date__c, opt => opt.MapFrom(src => src.ExpirationDate))
                .ForMember(dest => dest.File_Uploaded__c, opt => opt.MapFrom(src => src.FileUploaded))
                .ForMember(dest => dest.LicenseCertification_Status__c, opt => opt.MapFrom(src => src.LicenseCertificationStatus))
                .ForMember(dest => dest.LicenseCertification_Type__c, opt => opt.MapFrom(src => src.LicenseCertificationType))
                .ForMember(dest => dest.License_Types_LARA__c, opt => opt.MapFrom(src => src.LicenseTypesLARA)).ReverseMap();

            CreateMap<PractitionerPSV, PractitionerPSVDto>()
                .ForMember(dest => dest.Credentialing_Profile__c, opt => opt.MapFrom(src => src.CredentialingProfile))
                .ForMember(dest => dest.Primary_Source_Verifier_c, opt => opt.MapFrom(src => src.PrimarySourceVerifier))
                .ForMember(dest => dest.CVO__c, opt => opt.MapFrom(src => src.CVO))
                .ForMember(dest => dest.Other_Accred__c, opt => opt.MapFrom(src => src.OtherAccred))
                .ForMember(dest => dest.Verifier_s_Credentialing_Organization__c, opt => opt.MapFrom(src => src.VerifiersredentialingOrganization))
                .ForMember(dest => dest.Ichat_Background_Check__c, opt => opt.MapFrom(src => src.IchatBackgroundheck))
                .ForMember(dest => dest.Workforce_Background_Check__c, opt => opt.MapFrom(src => src.WorkforceBackgroundheck))
                .ForMember(dest => dest.Medicare_Base_Enrollment__c, opt => opt.MapFrom(src => src.MedicareBaseEnrollment))
                .ForMember(dest => dest.Medicare_Opt_Out__c, opt => opt.MapFrom(src => src.MedicareOptOut))
                .ForMember(dest => dest.LARA_License__c, opt => opt.MapFrom(src => src.LARALicense))
                .ForMember(dest => dest.LARA_Uploaded__c, opt => opt.MapFrom(src => src.LARAUploaded))
                .ForMember(dest => dest.Official_Transcript_from_Accredited_Scho__c, opt => opt.MapFrom(src => src.OfficialTranscriptfromAccreditedScho))
                .ForMember(dest => dest.Degree_Verification__c, opt => opt.MapFrom(src => src.DegreeVerification))
                .ForMember(dest => dest.AMA_Verification__c, opt => opt.MapFrom(src => src.AMAVerification))
                .ForMember(dest => dest.AOA_Verification__c, opt => opt.MapFrom(src => src.AOAVerification))
                .ForMember(dest => dest.MDHHS_Sanctioned_Provider_Check__c, opt => opt.MapFrom(src => src.MDHHSSanctionedProviderheck))
                .ForMember(dest => dest.MCBAP_Verification__c, opt => opt.MapFrom(src => src.MCBAPVerification))
                .ForMember(dest => dest.Office_of_Inspector_General_Check__c, opt => opt.MapFrom(src => src.OfficeofInspectorGeneralheck))
                .ForMember(dest => dest.SAM_gov_Check__c, opt => opt.MapFrom(src => src.SAMgovheck))
                .ForMember(dest => dest.National_Sex_Offender_Registry_Check__c, opt => opt.MapFrom(src => src.NationalSexOffenderRegistryheck))
                .ForMember(dest => dest.MI_Public_Sex_Offender_Registry_Check__c, opt => opt.MapFrom(src => src.MIPublicSexOffenderRegistryheck))
                .ForMember(dest => dest.ECFMG__c, opt => opt.MapFrom(src => src.ECFMG)).ReverseMap();

            CreateMap<PractitionerCP, PractitionerCPDto>()
                .ForMember(dest => dest.First_Name__c, opt => opt.MapFrom(src => src.FirstName))
                .ForMember(dest => dest.Last_Name__c, opt => opt.MapFrom(src => src.LastName))
                .ForMember(dest => dest.Date_of_Birth__c, opt => opt.MapFrom(src => src.DateofBirth))
                .ForMember(dest => dest.Tax_ID__c, opt => opt.MapFrom(src => src.TaxID))
                .ForMember(dest => dest.Medicare_Provider__c, opt => opt.MapFrom(src => src.MedicareProvider))
                .ForMember(dest => dest.Medicare_Number__c, opt => opt.MapFrom(src => src.MedicareNumber))
                .ForMember(dest => dest.Practitioner_NPI__c, opt => opt.MapFrom(src => src.PractitionerNPI))
                .ForMember(dest => dest.Office_Address_Street_1__c, opt => opt.MapFrom(src => src.OfficeAddressStreet1))
                .ForMember(dest => dest.Office_Address_City__c, opt => opt.MapFrom(src => src.OfficeAddressCity))
                .ForMember(dest => dest.Office_Address_Zipcode__c, opt => opt.MapFrom(src => src.OfficeAddressZipcode))
                .ForMember(dest => dest.Office_Address_State__c, opt => opt.MapFrom(src => src.OfficeAddressState))
                .ForMember(dest => dest.Office_Address_County__c, opt => opt.MapFrom(src => src.OfficeAddressCounty))
                .ForMember(dest => dest.Home_Address_Street_1__c, opt => opt.MapFrom(src => src.HomeAddressStreet1))
                .ForMember(dest => dest.Home_Address_City__c, opt => opt.MapFrom(src => src.HomeAddressCity))
                .ForMember(dest => dest.Home_Address_Zipcode__c, opt => opt.MapFrom(src => src.HomeAddressZipcode))
                .ForMember(dest => dest.Home_Address_State__c, opt => opt.MapFrom(src => src.HomeAddressState))
                .ForMember(dest => dest.Home_Address_County__c, opt => opt.MapFrom(src => src.HomeAddressCounty))
                .ForMember(dest => dest.Specialties__c, opt => opt.MapFrom(src => src.Specialties))
                .ForMember(dest => dest.Other_Specialty__c, opt => opt.MapFrom(src => src.OtherSpecialty))
                .ForMember(dest => dest.Certificate_of_Liability__c, opt => opt.MapFrom(src => src.CertificateofLiability))
                .ForMember(dest => dest.Certificate_of_Liability_Expiration_Date__c, opt => opt.MapFrom(src => src.CertificateofLiabilityExpirationDate))
                .ForMember(dest => dest.Current_Malpractice_Insurance_Coverage__c, opt => opt.MapFrom(src => src.CurrentMalpracticeInsuranceCoverage))
                .ForMember(dest => dest.Malpractice_Insurance_Coverage_Status__c, opt => opt.MapFrom(src => src.MalpracticeInsuranceCoverageStatus))
                .ForMember(dest => dest.Explanation_Current_Malpractice__c, opt => opt.MapFrom(src => src.ExplanationCurrentMalpractice))
                .ForMember(dest => dest.MalpracticeInsurance_Coverage_Expiration__c, opt => opt.MapFrom(src => src.MalpracticeInsuranceCoverageExpiration))
                .ForMember(dest => dest.Languages_Spoken__c, opt => opt.MapFrom(src => src.LanguagesSpoken))
                .ForMember(dest => dest.Cultural_Competences__c, opt => opt.MapFrom(src => src.CulturalCompetences))
                .ForMember(dest => dest.Five_year_work_history__c, opt => opt.MapFrom(src => src.Fiveyearworkhistory))
                .ForMember(dest => dest.X6_month_gap_in_employment_since_profess__c, opt => opt.MapFrom(src => src.X6monthgapinemploymentsinceprofess))
                .ForMember(dest => dest.X6_Month_Gap_Start_Date__c, opt => opt.MapFrom(src => src.X6MonthGapStartDate))
                .ForMember(dest => dest.X6_Month_Gap_End_Date__c, opt => opt.MapFrom(src => src.X6MonthGapEndDate))
                .ForMember(dest => dest.X6_Month_Gap_Activity__c, opt => opt.MapFrom(src => src.X6MonthGapActivity))
                .ForMember(dest => dest.X6_Month_Gap_Reason__c, opt => opt.MapFrom(src => src.X6MonthGapReason))
                .ForMember(dest => dest.Please_acknowledge_If_denied_credential__c, opt => opt.MapFrom(src => src.PleaseacknowledgeIfdeniedcredential))
                .ForMember(dest => dest.Can_you_perform_the_essential_duties_of__c, opt => opt.MapFrom(src => src.Canyouperformtheessentialdutiesof))
                .ForMember(dest => dest.Reason_for_inability_to_perform_essentia__c, opt => opt.MapFrom(src => src.Reasonforinabilitytoperformessentia))
                .ForMember(dest => dest.Lack_of_present_illegal_drug_use__c, opt => opt.MapFrom(src => src.Lackofpresentillegaldruguse))
                .ForMember(dest => dest.Explanation_Lackofpresentillegaldrug__c, opt => opt.MapFrom(src => src.ExplanationLackofpresentillegaldrug))
                .ForMember(dest => dest.History_of_loss_of_license__c, opt => opt.MapFrom(src => src.Historyoflossoflicense))
                .ForMember(dest => dest.ExplanationHistoryoflossoflicense__c, opt => opt.MapFrom(src => src.ExplanationHistoryoflossoflicense))
                .ForMember(dest => dest.History_of_felony_convictions__c, opt => opt.MapFrom(src => src.Historyoffelonyconvictions))
                .ForMember(dest => dest.ExplanationHistory_of_felony_convictions__c, opt => opt.MapFrom(src => src.ExplanationHistoryoffelonyconvictions))
                .ForMember(dest => dest.History_of_loss_or_limitations_of_privil__c, opt => opt.MapFrom(src => src.Historyoflossorlimitationsofprivil))
                .ForMember(dest => dest.ExplanationHistory_of_loss__c, opt => opt.MapFrom(src => src.ExplanationHistoryofloss))
                .ForMember(dest => dest.Attestation_by_the_applicant_of_the_corr__c, opt => opt.MapFrom(src => src.Attestationbytheapplicantofthecorr))
                .ForMember(dest => dest.Cultural_Competencies_Picklist__c, opt => opt.MapFrom(src => src.CulturalCompetenciesPicklist)).ReverseMap();

        }
    }
}
