name: CI/CD PipeLine

on:
 push:
   branches:[main]

   jobs:
      build:
        runs-on: window-latest
        steps:
        - name: Checkout code
          run: dotnet build --configuration Release
          
       -  name: dotnet publish
          run: dotnet publish -c Release -0 ${{env.DOTNET_ROOT}}/Salesforce
